name: Spell Check

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository slug (user/repo)"
        required: true
        type: string

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Install cspell
        run: npm install -g cspell

      - name: Clone repository
        run: gh repo clone "${{ github.event.inputs.repository }}" target-repo
      - name: Set up Python $
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell
      - name: Check spelling with codespell
        working-directory: target-repo
        run: |
          find . -type f -regextype posix-egrep -regex ".*\.(mdx|md|txt)$" -exec codespell -w {} +
      - name: Run cspell on markdown files
        id: cspell
        working-directory: target-repo
        run: |
            echo "found_issues=true" >> "$GITHUB_OUTPUT"
     
      - name: Setup credentials to access private repositories
        run: |
          git config --global user.name "${{github.repository_owner}}"
          git config --global user.email "$(gh api user/public_emails -q '.[0].email')"
          git config --global url.https://${{ secrets.GH_PAT }}@github.com/.insteadOf https://github.com/

      - name: Fork repository
        if: steps.cspell.outputs.found_issues == 'true'
        working-directory: target-repo
        run: |
          gh repo fork "${{ github.event.inputs.repository }}" --clone=false
          REPO_NAME=$(echo "${{ github.event.inputs.repository }}" | cut -d'/' -f2)
          git remote set-url origin "https://github.com/${{ github.repository_owner }}/${REPO_NAME}.git"

      - name: Commit and push changes
        if: steps.cspell.outputs.found_issues == 'true'
        working-directory: target-repo
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changed files to commit"
          else
            git commit -m "docs: correct spelling"
            git push origin HEAD
          fi
